
replicaCount: 1


image:
  repository: nginx
  tag: latest
  pullPolicy: IfNotPresent


service:
  name: application-nodejs
  type: ClusterIP
  appLabel: application-nodejs
  port: 80
  targetPort: 3000
#   node
 
# LGTM stack

# loki 
# grafana
# tempo
# mimir

# gateway-api
# ingress 
deployment:
  name: application-nodejs
  replicas: 7
  appLabel: application-nodejs

container:
  name: application-nodejs
  image: israel442/node-hello-service
  tag: latest
  pullPolicy: Always
  port: 3000


ingress:
  enabled: false
  host: example.com



