
replicaCount: 1


image:
  repository: nginx
  tag: latest
  pullPolicy: IfNotPresent


service:
  name: application-nodejs
  type: NodePort
  appLabel: application-nodejs
  port: 80
  targetPort: 3000
  nodePort: 30080

deployment:
  name: application-nodejs
  replicas: 1
  appLabel: application-nodejs

container:
  name: application-nodejs
  image: israel442/node-hello-service
  tag: latest
  pullPolicy: Always
  port: 3000


ingress:
  enabled: false
  host: example.com



