apiVersion: v1
kind: Service
metadata:
  name: application-nodejs
spec:
  type: NodePort
  selector:
    app: application-nodejs
  ports:
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 30080
